### ISSUE TITLE
command.askPass and command.askSudoPass method - giving TypeError

### ISSUE THREAD

**Issue by iamsgsn** [shaharke/node-ansible#37]
Hi Team,

Thanks for the splendid node package for ansible. I am having issues while specifying askPass and askSudoPass method. It gives me the below error. Let me know if i am missing anything here.
TypeError: command.askPass is not a function
    at Object.<anonymous> (/Users/Sowmy/Desktop/Personal/02_MyLearings/nodejs/node-ansible.js:6:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by iamsgsn** [comment]
Here is my complete code

var Ansible = require('node-ansible');
var command = new Ansible.AdHoc().hosts('app-servers').module('shell').args('echo "hello"');
command.inventory('path to inventory');
command.user('****_');
command.su('**_*');
command.asSudo();
command.askPass();
command.askSudoPass();
command.verbose('vvvv');
var promise = command.exec();

It gives me the below error
TypeError: command.askPass is not a function
    at Object.<anonymous> (/Users/Sowmy/Desktop/Personal/02_MyLearings/nodejs/node-ansible.js:6:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by minademian** [comment]
Hi, @iamsgsn. I'm a new maintainer for this project. Are you still having problems with this code? I do realize that this was a long time ago!

**Comment by AndriesN** [comment]
This is a very old post but I'm gonna try it anyway. I have exactly the same problem as described above. Did I do anything wrong?

Thanks.
